### PR TITLE
rpc: url.Parse can't parse filepath in windows

### PR DESCRIPTION
**Pull request by jsvisa**
As #17141 said, CI failed in Windowss after PR #17041 merged, because #17041 introduced a new test case `TestNewSwarm` in [swarm_test.go#L38](https://github.com/ethereum/go-ethereum/blob/master/swarm/swarm_test.go#L38), [diff](https://github.com/ethereum/go-ethereum/pull/17041/files#diff-a690be1dbdc6e4dac043558611dd8cfeR35). AFAIK, this bug exists for a long time, long before PR #17041, and it happened in that PR.

### CODE REVIEW

**Comment by jsvisa** [comment]
@karalabe as https://ci.appveyor.com/project/ethereum/go-ethereum/build/master.7006/job/tocjijjprtmv4tac#L1227 said: 
> swarm_test.go:175: error connecting to SWAP API C:\Users\appveyor\AppData\Local\Temp\1\swarm837570684/TestSwarm.ipc: no known transport for URL scheme "c"

**Comment by karalabe** [comment]
The test is supposedly fixed already on master.

**Comment by nonsense** [comment]
Fixed as part of b3711af05.
