### PR TITLE
fix compilation error on 2 fixed size arrays, type Hash and Address

### PR DESCRIPTION
**Pull request by bgrieder**
This fails to compile with Go 1.9.1

Since the the types `Hash` and `Address` are defined as arrays with respective fixed length `HashLength` and `AddressLength`,  the substitution should be fine

### CODE REVIEW

**Comment by GitCop** [comment]
Thank you for your contribution! Your commits seem to not adhere to the repository coding standards

 * Commit: bd88198e5b9e4d81e0fbdd96c84de66f271c04ba
  * Commits must be prefixed with the package(s) they modify

Please check the [contribution guidelines](https://github.com/ethereum/go-ethereum#contribution) for more details.

---
This message was auto-generated by https://gitcop.com

**Comment by fjl** [comment]
I can't reproduce the compilation failure.

**Comment by bgrieder** [comment]
OK. This may actually be a Gogland false positive (although it makes sense to me)

image

**Comment by karalabe** [comment]
You'll have to get this sorted out upstream with Gogland. According to the Go language specification, `len` should be able to work on an array https://golang.org/ref/spec#Length_and_capacity.

I think the ambiguity might come from the fast that the spec isn't clear what happens with type aliases. However, given that Go itself compiles fine, I'd rather get Gogland fixed, not this particular instance of the false positive.

**Comment by bgrieder** [comment]
Fine, thanks! Will report to Gogland
