### ISSUE TITLE
Geth build failed error 2

### ISSUE THREAD

**Issue by chyand** [ethereum/go-ethereum#2092]
Running go-ethereum on Ubuntu Trusty Tahr 14.04
Running for months, then after a recent update, I uninstalled some libraries (sudo apt-get purge ethminer eth libethereum) from an initial build because my gpus would not connect. 

I resolved to create another mining instance. I created a new directory and new miner, however, I can not make geth. I get a geth error 2. Here is the make, with errors (after the 2nd runtime):

newInstall/go-ethereum$ make geth ...
newInstall/go-ethereum$ make geth
build/env.sh go install -v -ldflags '-X main.gitCommit 54904...8' -tags opencl ./cmd/geth
crypto/rsa
runtime/trace
# runtime/trace
/usr/lib/go/src/runtime/trace/trace.go:23: undefined: runtime.StartTrace
/usr/lib/go/src/runtime/trace/trace.go:28: undefined: runtime.ReadTrace
/usr/lib/go/src/runtime/trace/trace.go:41: undefined: runtime.StopTrace
# crypto/rsa
/usr/lib/go/src/crypto/rsa/rsa.go:93: undefined: crypto.DecrypterOpts
/usr/lib/go/src/crypto/rsa/rsa.go:98: use of .(type) outside type switch
make: *** [geth] Error 2

UPDATE 1: I went back to the original go-ethereum build, re-installed cpp-ethereum, and the GPUs are at least connecting now. Initial JSON-RPC error, then connecting and after loading miner header, get a BUS error, and fails. Restarted miners, DAG loaded, everything is running fine. No more hashrate display, however. So far so good with the cpp-ethereum re-install.

Here is the full build text:

make geth
build/env.sh go install -v -ldflags '-X main.gitCommit 5490437...8' -tags opencl ./cmd/geth
github.com/codegangsta/cli
github.com/Gustav-Simonsson/go-opencl/cl
github.com/ethereum/go-ethereum/rlp
github.com/ethereum/go-ethereum/crypto/ecies
github.com/ethereum/go-ethereum/crypto/sha3
github.com/pborman/uuid
golang.org/x/crypto/pbkdf2
golang.org/x/crypto/ripemd160
github.com/ethereum/go-ethereum/logger/glog
github.com/ethereum/go-ethereum/crypto/randentropy
github.com/ethereum/go-ethereum/crypto/secp256k1
golang.org/x/crypto/scrypt
github.com/ethereum/go-ethereum/params
github.com/hashicorp/golang-lru
github.com/rcrowley/go-metrics
github.com/syndtr/goleveldb/leveldb/util
github.com/syndtr/goleveldb/leveldb/comparer
github.com/syndtr/gosnappy/snappy
github.com/ethereum/go-ethereum/common
gopkg.in/karalabe/cookiejar.v2/collections/prque
github.com/syndtr/goleveldb/leveldb/cache
github.com/syndtr/goleveldb/leveldb/storage
github.com/syndtr/goleveldb/leveldb/filter
github.com/syndtr/goleveldb/leveldb/opt
github.com/ethereum/go-ethereum/event
gopkg.in/fatih/set.v0
crypto/rsa
# crypto/rsa
/usr/lib/go/src/crypto/rsa/rsa.go:93: undefined: crypto.DecrypterOpts
/usr/lib/go/src/crypto/rsa/rsa.go:98: use of .(type) outside type switch
github.com/huin/goupnp/scpd
golang.org/x/net/html/atom
golang.org/x/net/html
github.com/syndtr/goleveldb/leveldb/errors
github.com/ethereum/go-ethereum/logger
golang.org/x/text/transform
github.com/syndtr/goleveldb/leveldb/iterator
github.com/syndtr/goleveldb/leveldb/journal
golang.org/x/text/encoding
github.com/syndtr/goleveldb/leveldb/memdb
github.com/syndtr/goleveldb/leveldb/table
golang.org/x/text/encoding/internal/identifier
golang.org/x/text/encoding/internal
golang.org/x/text/encoding/unicode
golang.org/x/text/encoding/charmap
golang.org/x/text/encoding/japanese
github.com/ethereum/go-ethereum/metrics
golang.org/x/text/encoding/korean
golang.org/x/text/encoding/simplifiedchinese
github.com/syndtr/goleveldb/leveldb
golang.org/x/text/encoding/traditionalchinese
github.com/jackpal/go-nat-pmp
github.com/ethereum/go-ethereum/event/filter
github.com/robertkrimen/otto/file
github.com/robertkrimen/otto/token
github.com/robertkrimen/otto/ast
github.com/robertkrimen/otto/dbg
github.com/robertkrimen/otto/parser
github.com/robertkrimen/otto/registry
github.com/ethereum/go-ethereum/rpc/shared
github.com/ethereum/go-ethereum/rpc/codec
github.com/peterh/liner
github.com/mattn/go-isatty
github.com/ethereum/go-ethereum/ethdb
github.com/shiena/ansicolor
github.com/fatih/color
github.com/robertkrimen/otto
runtime/trace
# runtime/trace
/usr/lib/go/src/runtime/trace/trace.go:23: undefined: runtime.StartTrace
/usr/lib/go/src/runtime/trace/trace.go:28: undefined: runtime.ReadTrace
/usr/lib/go/src/runtime/trace/trace.go:41: undefined: runtime.StopTrace
github.com/mattn/go-runewidth
github.com/nsf/termbox-go
golang.org/x/net/html/charset
github.com/gizak/termui
github.com/ethereum/go-ethereum/jsre
github.com/ethereum/go-ethereum/crypto
github.com/ethereum/go-ethereum/core/vm
github.com/ethereum/go-ethereum/trie
github.com/ethereum/go-ethereum/accounts
github.com/ethereum/go-ethereum/common/compiler
github.com/ethereum/go-ethereum/common/registrar
github.com/ethereum/go-ethereum/rpc/useragent
github.com/ethereum/go-ethereum/core/types
github.com/ethereum/go-ethereum/core/state
github.com/ethereum/go-ethereum/pow
github.com/ethereum/go-ethereum/eth/downloader
github.com/ethereum/ethash
make: *** [geth] Error 2

**Comment by karalabe** [comment]
What Go version do you have installed? Seems to me that Go is either old, or the libraries went missing somehow.

**Comment by chyand** [comment]
Go is Version 1.4.0. I re-installed cpp-ethereum, and the gpus are communicating, and mining fine. Thank you.

**Comment by karalabe** [comment]
The things the failures are referencing were introduced in Go 1.5. However, Geth AFAIK can build with Go 1.4 too. It seems to me that some Go 1.5 libraries are listed somehow in a path that Go 1.4 picks up on your system. Please make sure you don't have two conflicting versions being used at the same time. Perhaps you installed Go from the official Ubuntu repos and a second version from the Ethereum repos, and the package manager didn't match them up properly?

**Comment by chyand** [comment]
For the initial install, I cloned Go from github: git clone
https://github.com/ethereum/go-ethereum. I also used the ethererum
repository: add-apt-repository ppa:ethereum/ethereum , and installed the
library: apt-get install -y build-essential libgmp3-dev golang.

This installation is a puzzle to me, and doesn't make a lot of sense,
because I used a guide for the go-ethereum installation. I am unsure how to
detect the library versions, or library store, in my current build, in
order to eliminate an offending library or reference. I'll search for
another reference regarding the library stores, however, the ethereum rig
is operational at this point.

Thank you for the information.

On Tue, Dec 29, 2015 at 2:16 AM, Péter Szilágyi <notifications@github.com>
wrote:

> The things the failures are referencing were introduced in Go 1.5.
> However, Geth AFAIK can build with Go 1.4 too. It seems to me that some Go
> 1.5 libraries are listed somehow in a path that Go 1.4 picks up on your
> system. Please make sure you don't have two conflicting versions being used
> at the same time. Perhaps you installed Go from the official Ubuntu repos
> and a second version from the Ethereum repos, and the package manager
> didn't match them up properly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ethereum/go-ethereum/issues/2092#issuecomment-167760955>
> .
>



-- 
Cheryl Anderson
