### PR TITLE
p2p/simulations: Various fixes

### PR DESCRIPTION
**Pull request by lmars**
Taken from https://github.com/ethersphere/go-ethereum/pull/119.

This PR includes a hack to force a re-dial when adding static peers (9184728), as sometimes re-dials don't happen in large simulations.

This was discussed between me, @zelig and @fjl where I proposed adding a separate `DialPeer` function to the `p2p.Server` but after attempting to do so it seems to be more work than originally thought. We need to make a decision on whether this hack can be merged as is, and if not then decide how to proceed.

### CODE REVIEW

**Comment by zelig** [comment]
@fjl please advise on this. what should happen with the HACK commit?

**Comment by fjl** [comment]
Sorry, I was super busy. I don't like the HACK commit.

**Comment by lmars** [comment]
Some thoughts from a [discussion in the orange-lounge gitter channel](https://gitter.im/ethersphere/orange-lounge?at=5a05d6b7614889d47564b459) about replacing the "hack" commit with something better:

---

The hive code currently tries to dial peers which it should be connected to but isn't currently, and it does this by calling `p2p.Server.AddPeer`, but `AddPeer` doesn't always dial a peer, it just adds the peer to a static list of peers that it believes it should redial at some point in the future, and under some conditions the peer never gets dialled.

What we want is a `DialPeer` method which just attempts to do a dial every time it is called, and then the hive can manage doing the retries (this is what we discussed with @fjl and he was happy with the plan, I just didn't have the time to implement it).

More longer term, we would really like to have what is outlined in #2254.

---

**Comment by nonsense** [comment]
There are a few todos on this PR:
- [ ] `srv.log` is nil in tests, causing them to crash
- [ ] `net.Pipe` does not support write deadline, causing `rlpx_test.go` to fail (because of 3348b90786f8ba63b9e66374031ea9843ec438aa). Switching to `tcpPipe` appears to be flaky - working most of the time, but also crashing on occasion.
```
--- FAIL: TestProtocolHandshake (0.01s)
        rlpx_test.go:216: error receiving disconnect: read tcp 127.0.0.1:53210->127.0.0.1:53209: use of closed network connection
FAIL
FAIL    github.com/ethereum/go-ethereum/p2p     1.723s
```
- [ ] address `HACK` commit

I will look into addressing these.

**Comment by nonsense** [comment]
Rebased on `go-ethereum/master` and reverted the `HACK` commit.

**Comment by nonsense** [comment]
I have addressed the TODOs mentioned above in the following way:
1. `HACK` commit - I don't know why this was necessary in the first place. I believe it was added due to `TestDiscoverySimulationExecAdapter` (which is not part of this PR) failing, but ultimately the commit is not needed in my opinion.
2. `srv.log` is nil in tests, causing them to crash - I initialised the logger for each `Server` as part of the tests. `srv.log` was added so that we have a unique server ID per server instance, when running multiple instances in simulation tests.
3. `SetWriteDeadline` error handling has been reverted as well, because we use `SetWriteDeadline` at multiple places, but this is the only place where we check for error. If we want to handle it, we should handle it everywhere (which appears to be out-of-scope for this PR). Furthermore `net.Pipe` does not support it, so we'd have to amend all tests to use another pipe altogether. I believe the error check was added because of deadlocks in simulation tests, but I think this is independent of the `SetWriteDeadline` error check.

**Comment by nonsense** [comment]
@lmars @fjl this is ready for review. The failures in CI appear to be unrelated to this PR.
