### ISSUE TITLE
Vendoring fails on projects using the native Golang bindings

### ISSUE THREAD

**Issue by awishformore** [ethereum/go-ethereum#2738]
#### System information

```
Geth
Version: 1.4.7-stable-667a386d
Protocol Versions: [63 62 61]
Network Id: 1
Go Version: go1.6.2
OS: linux
GOPATH=/home/awishformore/Code/go
GOROOT=/opt/google/go
```
#### Expected behaviour

I am using the Golang native contract bindings in a project. The project builds fine. I want to use vendoring to add all dependencies into the repository and have it build in an isolated fashion. Using `godep save` should add all required dependencies to the vendor folder.
#### Actual behaviour

`godep save` misses some cgo dependencies that are located in their own folder. This causes the build to fail with:

```
vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/curve.go:43:44: fatal error: libsecp256k1/include/secp256k1.h: No such file or directory
 #include "libsecp256k1/include/secp256k1.h"
                                            ^
compilation terminated.
```

The problem is described in the following issue on the Godep repository: https://github.com/tools/godep/issues/422

The sqlite library in Go solved the issue by putting the cgo dependencies into the same package as the files that depend on it.
#### Steps to reproduce the behaviour
- use automatically generated Golang bindings in a project
- bind a contract using the native binding, an address and a backend
- use `godep save` to save the dependencies in the vendor folder
- attempt a build with `go build` on Golang version 1.6 or later

**Comment by awishformore** [comment]
Still an issue.

**Comment by LYY** [comment]
Still have same issue.

**Comment by kjda** [comment]
me too

**Comment by lmars** [comment]
A temporary solution is to just manually copy the files into vendor:

```
cp -r \
  "${GOPATH}/src/github.com/ethereum/go-ethereum/crypto/secp256k1/libsecp256k1" \
  "vendor/src/github.com/ethereum/go-ethereum/crypto/secp256k1/"
```

**Comment by Freyert** [comment]
@lmars you ... I can't even... wow... thanks! For any newbz out there like myself who have been privileged enough to grow up on `dep ensure` you should do a:

```
go get github.com/ethereum/go-ethereum
```
before running the above.

**Comment by nfeld9807** [comment]
I think the issue is more along the lines of dep, see this issue: https://github.com/golang/dep/issues/1847

**Comment by saan099** [comment]
Same thing with govendor.

**Comment by nkashy1** [comment]
Had this error using `dep`. Thanks @lmars

**Comment by ezynda3** [comment]
Is there a plan to fix this?

**Comment by engenegr** [comment]
@ezynda3 it is more likey golang bug. or dep. or whatever, i encountered the same problems with ledger-related golang code.

**Comment by zglzglak47** [comment]
if you are using govendor , try  "govendor fetch -tree  github.com/ethereum/go-ethereum/crypto/secp256k1"

**Comment by karalabe** [comment]
Hey, so this is a limitation of the Go vendoring ecosystem. The suggested workaround by @zglzglak47 is **the** correct solution unfortunately. Maybe go 1.11 modules could eventually help, but for now this is an unfortunate limit of Go.

**Comment by huahuayu** [comment]
> if you are using govendor , try "govendor fetch -tree github.com/ethereum/go-ethereum/crypto/secp256k1"

it works!
