### ISSUE TITLE
Compile errors with golang 1.18. Need to stop using atomic.Pointer or change README.md so minimal golang required is updated. Please note requiring golang upgrade would "break" Ubuntu LTS.

### ISSUE THREAD

**Issue by J-A-M-E-5** [ethereum/go-ethereum#26789]
Compile error:-
`core/blockchain.go:202:27: undefined: atomic.Pointer`

Same thing happened a few weeks ago here: https://github.com/ethereum/go-ethereum/issues/26679

Users of Ubuntu 22.04 LTS now have to compile a new version of go as the repo version is 1.18. Or these changes need to be backed out which is what happened 2 weeks ago. Can your automated builds not use 1.18 to spot these errors, until you decide to no longer support 1.18?

**Comment by J-A-M-E-5** [comment]
This appears to be the change that broke it: https://github.com/ethereum/go-ethereum/pull/26777

**Comment by karalabe** [comment]
Bumped the minimum version to Go 1.19 so there's no more confusion.
